# If someone with write access comments "/chromatic-test" on a pull request, emit a repository_dispatch event

name: 'UI Tests with Chromatic'

on:
  push:
    paths:
      - packages/design-system/**'
  pull_request:
    paths:
      - packages/design-system/**'
  issue_comment:
    types: [ created ]

defaults:
  run:
    working-directory: packages/design-system

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout PR if pull_request event
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Checkout PR if push event
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        uses: actions/checkout@v1

      - name: Publish to Chromatic
        id: chromatic-publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.ADS_CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: "build"

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          token: ${{ env.TOKEN }} # GitHub App installation access token
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: |
            chromatic-test
          permission: write
