name: Deploy Design System Storybook

on:
  push:
    paths:
      - "packages/design-system/**"
    branches:
      - "main"

# Change the working directory for all the jobs in this workflow
defaults:
  run:
    working-directory: packages/design-system

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Setup node with version 16.x and NPM registry url
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      # yarn build to build the project
      - name: Build package
        run: yarn build-storybook

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.APPSMITH_DESIGN_SYSTEM_AWS_ROLE}}
          role-session-name: ds-storybook-deploy-workflow
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 sync storybook-static s3://design-system.appsmith.com/ --recursive
