name: Deploy Design System Storybook

on:
  push:
    paths:
      - "packages/design-system/**"
    branches:
      - "release"

# Change the working directory for all the jobs in this workflow
defaults:
  run:
    working-directory: packages/design-system

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Setup node with version 16.x and NPM registry url
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      
      # Get yarn cache directory and set it in a variable
      - name: Get yarn cache path
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      # Load yarn cache
      - name: Load Yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      # Install the dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # yarn build to build the project
      - name: Build package
        run: yarn build-storybook
