# Workflow trigger on any push and pull request.
# For now this will only run on commenting /build-design-system
name:  Test, build and push

on:
#  push:
#    branches: [ release, main ]
#    paths:
#      - "packages/design-system/**"
  issue_comment:
    types: [ created ]

# Change the working directory for all the jobs in this workflow
defaults:
  run:
    working-directory: packages/design-system

# Job will run on a ubuntu instance
jobs:
  build-design-system:
    uses: ./.github/workflows/Lib-build-design-system.yml
    name: build-design-system
  
  PushCheck:
    needs: [build-design-system]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo "All ui-test matrices completed"
